services:
  redis:
    image: redis:latest
    container_name: container_redis
    ports:
      - "6379:6379"
    environment:
      - CONTAINER_PORT=6379
      - HOST_PORT=6379
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "7861:7861"
    container_name: container_backend
    environment:
      - CONTAINER_PORT=7861
      - HOST_PORT=7861
    volumes:
      - ./backend:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/cloud/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "7860:7860"
    container_name: container_frontend
    depends_on:
      - backend
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - CONTAINER_PORT=7860
      - HOST_PORT=7860
    volumes:
      - ./frontend:/usr/src/app
      - /home/cloud/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "1370:1370"  # Map the custom port (1370) to the host
    volumes:
      - /path/to/models:/app/model  # Mount your model directory
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True  # Reduce memory fragmentation
      - MAX_JOBS=1
    command: [
      "--model", "nm-testing/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic",
      "--max-model-len", "8192",
      "--cpu-offload-gb", "0",
      "--enforce-eager",
      "--enable-prefix-caching",
      "--tensor-parallel-size", "2",
      "--kv-cache-dtype", "fp8",
      "--port", "1370",
      "--swap-space", "2",
      "--gpu-memory-utilization", "0.95",
      "--served-model-name", "deepseek",
      "--enable-chunked-prefill",
      "--trust-remote-code"
    ]
    icp: host,
    restart: unless-stopped